### ISSUE TITLE
Release auto plugin support?

### ISSUE THREAD

**Issue by simonbeckett** [gilt/sbt-newrelic#17]
I'm running in to issues trying to get sbt-native-packager 1.0.0-m4 (needed due to recent docker update forcing -f for tag updates) to co-operate with gsbt-newrelic (which i'd like to keep using as it was perfect for my needs pre 1.0.0-m4).

`java.lang.NoSuchMethodError: com.typesafe.sbt.SbtNativePackager$.NativePackagerKeys()Lcom/typesafe/sbt/packager/Keys$;
	at com.gilt.sbt.newrelic.NewRelic$.packagerSettings(NewRelic.scala:57)`

I'm assuming that the current failure is due to the changes in native packager. Any plans to release your updates any time soon?

**Comment by mgillis** [comment]
It's not autoplugin support that's needed, the title of this is wrong -- it's just that the API has changed in sbt-native-packager between v0 and v1. I'm not sure native packager v1 is really ready for primetime in a lot of ways...

**Comment by simonbeckett** [comment]
Thanks Michael,

Fair enough regarding autoplugin support. I’m still very VERY green experience wise with sbt.
I’m kind of stuck between a rock and a hard place when it comes to sbt-native-packager as 0.8 was working nicely in conjunction with sbt-newrelic.
Recent updates to docker has forced us to either update native-packager, or implement some rather hacky non-sbt work arounds to glue the functionality back together.

You wouldn’t be able to advise me what changes we’d need to make to get sbt-newrelic working with native-packager v1 would you?

Thanks for your response

**Comment by igmar** [comment]
The new packager is to be included in Play 2.4. It already stops working with the RC releases. Please update it to support the newer version.

**Comment by fiadliel** [comment]
@igmar Please try version 0.1.0 and let me know if it works for you?

**Comment by igmar** [comment]
I'll try it

**Comment by fiadliel** [comment]
I am considering this fixed.

**Comment by igmar** [comment]
It works indeed. New Relic is however broken with Play 2.4.

**Comment by fiadliel** [comment]
Ah, this one: https://discuss.newrelic.com/t/metrics-not-shown-for-play-2-4/26637
If any workaround becomes viable, we could try and add it, but I'm not aware of any.
