### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by fajarmf** [gilt/sbt-newrelic#22]
I have installed this plugin, modify build.sbt and plugins.sbt.

After that, can I just need to re-run my play app with `sbt run`? Or do I need to install java agent too?

**Comment by fiadliel** [comment]
Hi,
the plugin is for creating production deployments which are integrated with New Relic. So it adds the New Relic agent to the deployments created by sbt-native-packager. See http://www.scala-sbt.org/sbt-native-packager/ for some examples of what is possible with this.

You won't need to install any extra dependencies; this downloads and includes the appropriate New Relic support inside the deployment artifacts created by sbt-native-packager.

But `sbt run` is a development tool, not a production deployment mechanism. And monitoring on development systems isn't very interesting or useful. Therefore, it's not really high on my list of priorities to make this work with that command.

Does that answer your question?

**Comment by fajarmf** [comment]
Yes thank you for answering to my question.

So if I am deploying my app, I don't need to do these step:
https://docs.newrelic.com/docs/agents/java-agent/frameworks/aws-elastic-beanstalk-installation-java

**Comment by fiadliel** [comment]
Those instructions are for a Tomcat/servlet environment, so unless you've figured out a way to put Play on top of that, those instructions are irrelevant.

The most likely environment is the Docker one? You should need to do nothing extra, after configuring this plugin (though you won't get machine-level metrics). This plugin includes the newrelic library in the Docker image, and the startup script is modified to point to the library.

**Comment by fajarmf** [comment]
Yeah, exactly. I am not using Tomcat/servlet. I am using sbt docker:stage

**Comment by fajarmf** [comment]
I tried running `sbt start` on my machine. but I don't see any metrics on my newrelic account. is there any thing that I am missing?

**Comment by fiadliel** [comment]
This does not integrate with `sbt start`, which I would consider to be a command one might use on a development machine. This works with the output of `sbt dist` (from Play), or the sbt-native-packager targets (which are described at http://www.scala-sbt.org/sbt-native-packager/formats/)

**Comment by fiadliel** [comment]
You can test your integration using something like:

```
$ sbt universal:stage

cd target/universal/stage
bin/<myproject>
```

**Comment by fajarmf** [comment]
after I run `sbt universal:stage` I didn't see newrelic.yml get generated. Shouldn't I get one generated right?

**Comment by fiadliel** [comment]
I would expect that there would be a directory `target/universal/stage` after running that command. Underneath that directory should be files `newrelic/newrelic.jar` and `newrelic/newrelic.yml`. In addition, there should be a line in `bin/<script>` which looks like
```addJava "-javaagent:${app_home}/../newrelic/newrelic.jar"```

If this isn't what you can see:
 - Which of the above details are missing?
 - What version of the plugin are you using?
 - What versions of sbt-native-packager and/or Play are you using?
 - How have you configured the plugin?

**Comment by fajarmf** [comment]
Thanks for your reply,

I found there is `target/universal/stage` folder but there is no folder `newrelic` in there. the script also doesn't have `addJava "-javaagent..../newrelic.jar"`

I added `newrelicLicenseKey := Some("d2bea10815e092a9d615dbbd202468a8309550a8")` to the end of `build.sbt` and  on my `plugins.sbt` there are these two lines among other plugin that I am using.```
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "0.7.4")
addSbtPlugin("com.gilt.sbt" % "sbt-newrelic" % "0.0.8")```

**Comment by fiadliel** [comment]
Have you followed these instructions:

> To use the NewRelic settings in your project, add NewRelic.packagerSettings to your build. If you are manually adding sbt-native-packager archetypes, you should add this line after the archetype has set default values for settings.

> `NewRelic.packagerSettings`

SBT does not add anything "magically" to a project's settings unless you are using an `AutoPlugin`. And sbt-native-packager 0.7.4 is not an `AutoPlugin`; therefore, the version of sbt-newrelic that supports that version, also cannot be an `AutoPlugin`.

SBT settings are applied sequentially as they are found. sbt-native-packager (and, as a result, Play <= 2.3.x), initialise settings to default values, whereas this plugin appends values to those that are existing. But if you reverse the ordering, this plugin will add values that are then reset to the default. This plugin _must_ be initialised for Play/sbt-native-packager after they are initialised.

If you have a multi-project build, I am currently going to assume that you know how to modify the instructions for such a case... :smile:

Note this is much easier and safer for sbt-native-packager 1.0 because the AutoPlugin support adds an ordering for when settings are added/modified.

**Comment by fiadliel** [comment]
Please reopen if you have any further feedback, and I can try and help further. Or there is a Gitter channel.
