### ISSUE TITLE
I am not sure what to do next

### ISSUE THREAD

**Issue by matteomelani** [gilt/sbt-newrelic#44]
I have built my Play 2.6 app following your instructions but now it is not clear to me what I need to do next to run the agent?

I thought that it was enough just to start the app.

If I use the standard installation procedure by downloading the agent and adding a bunch of command line options to the application starter then everything works just fine.

Thank you for any help.

**Comment by fiadliel** [comment]
Hi Matt,
this plugin adds New Relic to the packaged artifact (RPMs, Deb, Docker, Universal deployments, etc.).

See https://www.playframework.com/documentation/2.6.x/Deploying

The idea is that New Relic is mainly for monitoring and alerting on production infrastructure, and in those cases, you do _NOT_ want to be running your Play application from inside SBT. You really really don't.

The plugin doesn't install New Relic for development mode for a few reasons:

 1. generally you don't want to mix development and production metrics
 1. you would have to run Play in forked JVM mode to add New Relic to the JVM, which hurts quick reloads, etc.

In those few times where you want to use New Relic with a development app, you can create a local copy of the deployment files with `sbt universal:stage`, and look at what's created in the `target/universal/stage` directory. The deployment in that directory will include the New Relic agent.

Please reply if you have any more questions.
