### ISSUE TITLE
Add scala_futures_as_segments configuration

### ISSUE THREAD

**Issue by sancheztavo** [gilt/sbt-newrelic#46]
Quoting [https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes/java-agent-3440](url), Since version 3.44.0, unlike previous versions of the agent, by default the agent will not report Scala Futures as transaction segments, and those Futures will not contribute to the transaction’s reported Total Time.
You can enable that instrumentation with the following setting in the following property in the configuration:
```
scala_futures_as_segments:
      enabled: true
```
We currently have no way of enabling it if we don't directly use a custom yml.

**Comment by fiadliel** [comment]
Hi,
I've added a setting for this, but would prefer not to release until after testing (that the config entry actually does what it's supposed to). Should release in the next day or two (though if you can build locally and verify, that would be great!)

**Comment by guizmaii** [comment]
Any news ?

**Comment by fiadliel** [comment]
Hi, this is available in version 0.2.4.

**Comment by fiadliel** [comment]
Please let me know if you see any issues.

**Comment by fiadliel** [comment]
Setting is:
```scala
newrelicFuturesAsSegments := true
```

**Comment by mattfeury** [comment]
any chance of this getting merged into the 1.x (play 2.5 supported) version? plugin is super simple so far and this would be v handy

**Comment by mattfeury** [comment]
hi @fiadliel hope this is ok, but we're stuck on play 2.5.x and would love future support so made a PR (#48) to cherry-pick that config option to 0.1.x branch. Hope we can get this merged and published!
